WIP: [deploy] Add ability to specify ssh port
wshihadeh/docker-deployment-action pull request #11
Opened 2020-10-31 16:26 UTC by r3cha

I’m testing it at this time, will update when all be done

2020-10-31 16:47 UTC, r3cha commented
Hello I saw this https://github.com/wshihadeh/docker-deployment-action/issues/8 issue bcs have same problem
Here is simple PR
I’ve just test it it works well

2020-10-31 19:43 UTC, wshihadeh commented
Thanks for the PR , but why the below config does not work for you ?

```
remote_docker_host: user@myswarm.com:456
```

Second , I think that you are missing some lines in your PR .ie 
https://github.com/wshihadeh/docker-deployment-action/blob/bd161443045e6fc51b34ffcb6c618b8a6b3598e2/docker-entrypoint.sh#L53

2020-10-31 20:20 UTC, r3cha commented
@wshihadeh Thanks I see it, now I got it for me host:port it won’t works because I set `copy_stack_file: true`
so as I understand from code it will use ssh & scp that not accept host with port like `host:port`

2020-11-01 20:11 UTC, wshihadeh commented
also https://github.com/wshihadeh/docker-deployment-action/blob/7f7346de1a3e8609a614f50e17267e6bfbcf5442/docker-entrypoint.sh#L83

2020-11-01 21:48 UTC, r3cha commented
> also
> 
> https://github.com/wshihadeh/docker-deployment-action/blob/7f7346de1a3e8609a614f50e17267e6bfbcf5442/docker-entrypoint.sh#L83

Thanks! updated

2020-11-02 07:46 UTC, wshihadeh requested changes

2020-11-02 07:46 UTC, wshihadeh commented on docker-entrypoint.sh
```suggestion

if [ -z "$INPUT_REMOTE_DOCKER_PORT" ]; then
  INPUT_REMOTE_DOCKER_PORT=22
fi
```

2020-11-02 08:55 UTC, r3cha commented on docker-entrypoint.sh
22 default was stetted at action.yml but ok
```
  remote_docker_port:
     description: Remote Docker ssh port ie (22)
     required: false
     default: '22'
```

2020-11-02 09:46 UTC, merged

2020-11-02 09:48 UTC, wshihadeh commented
merged and created a new release https://github.com/wshihadeh/docker-deployment-action/releases/tag/v2